snt_immobilier:
    resource: "@SNTImmobilierBundle/Resources/config/routing.yml"
    prefix:   /

snt_immobilier_bien:
    resource: "@SNTImmobilierBundle/Controller/FrontController.php"
    type:     annotation

